export const siteContent = {
  nav: {
    logo: 'P.B. Hines Foundation',
    links: [
      { label: 'Legacy', href: '#legacy' },
      { label: 'Family Tree', href: '#family-tree' },
      { label: 'Descendants', href: '#descendants' },
      { label: 'Education', href: '#education' },
    ],
  },
  hero: {
    eyebrow: 'Liberty County, Georgia · Est. 1845',
    title: 'Pompey B. Hines',
    accentTitle: 'Foundation',
    subtitle:
      'Born into slavery. Died owning more than 450 acres of land. Father of 17. Patriarch of over 800 living descendants.',
    dates: 'Aug. 16, 1845 · Jul. 5, 1919',
    quote: 'For building the roads that we have traveled to success',
    scrollLabel: 'Explore',
  },
  legacy: {
    label: 'Our Origin',
    title: 'A Legacy',
    accentTitle: 'Rooted',
    trailingTitle: 'in Faith & Determination',
    paragraphs: [
      'We trace our history to Liberty County, Georgia and the Sand Hills Plantation. On August 16, 1845, Pompey B. Hines was born into slavery. Upon his death on July 5, 1919, our father, Pompey B. Hines, had acquired more than 450 acres of land.',
      'He left a rich legacy as the father of 17 children. Today there are more than 800 living descendants of Pompey B. Hines. We are still searching for words that will express our gratitude.',
      'Our family is like an acorn left unattended in a field of tall grass, trampled on and moved around a bit. The winter was harsh and yet it endured. Now spring has come: a root sprouts, a stem appears, and it reaches for the sky. A tree is born. Not just any tree, but an oak tree.',
      'Pompey was born a slave. After the Civil War, life was unsettling, and the 1870 Census revealed him in Willie, Georgia, a small farming community in Liberty County. This is where he put his roots down. This is where our family tree began to grow.',
    ],
    stats: [
      { value: '450+', label: 'Acres Acquired' },
      { value: '17', label: 'Children' },
      { value: '800+', label: 'Living Descendants' },
      { value: '150+', label: 'College Degrees' },
    ],
  },
  familyTree: {
    label: 'The 17 Branches',
    title: 'Biographies of the',
    accentTitle: '17 Descendants',
    branches: [
      {
        id: 'theodore',
        tabLabel: 'Theodore Ball',
        name: 'Theodore Ball',
        treeNumber: 'Family Tree 1 of 17',
        dates: 'Born Mar. 15, 1874 · Died March 1943',
        paragraphs: [
          'Theodore Ball is the 1st child of Pompey B. Hines, born in Liberty County Georgia and died in Evans County Georgia. His mother is Delia Ball.',
          'Theodore owned more than 600 acres of land in Evans County; he was a farmer as well as an entrepreneur, owning several naval stores and a turpentine still that produced rosin.',
          'He was a member of Jerusalem Baptist Church, serving as Secretary, Deacon, and Trustee. In 1941, when the Federal Government seized his land and the land of Jerusalem Baptist Church, he served on the committee for relocating the church from Liberty County to its present location in Bryan County, Georgia.',
          'Theodore Ball married Sarah Barnett, producing 3 children: Ludelia, Ollie, and Richard (Bud) Ball. After Sarah\'s death he married Buelah Holland. This union produced 14 children, 7 of whom died in infancy. The 7 children who lived are Joe T., Avis, W. Hardin, Milla Nease, Overidia, Gwendolyn, and Theddeus.',
          'He was 68 years old at the time of death.',
        ],
      },
      {
        id: 'arlene',
        tabLabel: 'Arlene Hines',
        name: 'Arlene Hines Johnson',
        treeNumber: 'Family Tree 2 of 17',
        dates: 'Born Apr. 23, 1874 · Died Dec. 10, 1960',
        paragraphs: [
          'Arlene Hines was born in Liberty County Georgia and died in Pembroke, Georgia. She was the first child born to Ellen and Pompey B. Hines.',
          'Arlene married Samuel Johnson on Feb. 11, 1898, likely in a church wedding, as the marriage license was signed by Rev. S. M. Walker, Pastor of Jerusalem Baptist Church. Brothers Samuel and Houston Johnson felt fortunate when they came upon the Pompey B. Hines household and found it full of fine women. They chose the two oldest, Arlene and Bessie. The two brothers married the two sisters, using the same pastor, three years apart.',
          'The newlyweds moved to Groveland, Georgia, where they became farmers. This marriage did not produce any children, but they were fortunate enough to raise two girls: Annalyzer and Alzader.',
          'She lived to be 95 years old, longer than any of her siblings.',
        ],
      },
      {
        id: 'julian',
        tabLabel: 'Julian H. Hines',
        name: 'Julian H. Hines',
        treeNumber: 'Family Tree 3 of 17',
        dates: 'Born Nov. 7, 1875 · Died Nov. 19, 1967',
        paragraphs: [
          'Julian H. Hines was born in Liberty County Georgia and died in Bulloch County Georgia. He stood 6 feet tall, very wiry, medium complexion, with an uncompromising demeanor. He was the 1st boy born to Ellen and Pompey B. Hines.',
          'Julian was Pompey Hines\' lieutenant, the one person Pompey could count on to get the job done. His brother Doyle said, "if papa left in the morning and told Bulb (Julian\'s nickname) to stand by the gate until he returned, then Bulb would still be standing there when Papa returned that night." His siblings did not challenge him; they gave him all the respect a big brother deserved.',
          'Julian married Christchaue George on Dec. 22, 1903, and this marriage produced 9 children. In 1941 the Federal Government seized his land in Liberty County for military use. The family moved to Bulloch County Georgia, where Julian purchased 205 acres from H.C. Burney and turned a small farm into a big, successful farming operation.',
          'He was a devoted Christian and Chairman of the Deacon Board at Jerusalem Baptist Church. He was 92 years old at the time of death.',
        ],
      },
      {
        id: 'bessie',
        tabLabel: 'Bessie Hines',
        name: 'Bessie Hines Johnson',
        treeNumber: 'Family Tree 4 of 17',
        dates: 'Born Apr. 17, 1876 · Died Nov. 1964',
        paragraphs: [
          'Bessie Hines was born in Liberty County Georgia and died in Pembroke, Georgia. She was the 2nd girl born to Ellen and Pompey Hines. Most of the children were light brown in complexion, but Bessie had a very light complexion with long black curly hair.',
          'When someone asked her brother Doyle, "is Bessie the prettiest of all your sisters?" Doyle replied, "at least she thinks that she is the prettiest."',
          'Bessie married Houston Johnson on May 12, 1901. She was ahead of her time, a socialite even though there was poverty all around her. Her furniture was top of the line; her clothing was far beyond what the women of her community were wearing. When everyone came to church on Sunday riding in old wooden wagons pulled by mules, Bessie came in a buggy with leather upholstery pulled by a horse. She was always immaculately dressed, and it was said she once vacationed in Florida with Madame Walker.',
          'She was 88 years old at the time of death.',
        ],
      },
      {
        id: 'delburgh',
        tabLabel: 'Delburgh Hines',
        name: 'Delburgh Hines',
        treeNumber: 'Family Tree 5 of 17',
        dates: 'Born Jun. 17, 1879 · Died Jan. 7, 1901',
        paragraphs: [
          'Delburgh Hines was born in Liberty County Georgia and died there at the age of 22. He was the 4th child of Ellen and Pompey Hines. It is thought he died of fever. He never married and had no children.',
        ],
      },
      {
        id: 'abbie',
        tabLabel: 'Abbie Hines',
        name: 'Abbie Hines Clanton',
        treeNumber: 'Family Tree 6 of 17',
        dates: 'Born Nov. 12, 1881 · Died Feb. 28, 1963',
        quoteAfterParagraph: 3,
        paragraphs: [
          'Abbie Hines was born in Liberty County Georgia and died in Pembroke, Georgia. She was a person of medium height and weight, very quiet but extremely focused. She was 2nd in command among her siblings, next to Julian Hines.',
          'When her mother Ellen died in 1900, only one of the 16 children was married, and there were 12 children under 19 years old, five of them under 6. Abbie became their surrogate mother.',
          'Abbie married Julian H. Clanton on March 11, 1905. The newlyweds moved to Pembroke, Georgia, where all 11 of their children were born. Abbie and Hardrick Clanton donated approximately 10 acres of land to the Bryan County Board of Education for the purpose of building a school for Black children. This land was occupied by Pembroke High School until the mid-1960s.',
          'She was a devoted, lifelong member of Jerusalem Baptist Church. She was 82 years old at the time of death.',
        ],
        quote:
          '"My mother, Esther Hines Simmons, told me she would hate to see her sister Abbie come home. After she got married she would come home and stay for a week or more washing dirty clothes, cleaning house and making quilts... we would be glad to see her leave."   Lillie Simmons Upshaw',
      },
      {
        id: 'annie',
        tabLabel: 'Annie Hines',
        name: 'Annie Hines Levant',
        treeNumber: 'Family Tree 7 of 17',
        dates: 'Born Jan. 1, 1884 · Died Apr. 12, 1973',
        quoteAfterParagraph: 3,
        paragraphs: [
          'Annie Hines was born in Liberty County Georgia. She was the 6th child and 4th girl in the family of 16. She was a person of medium height and weight with a mild disposition.',
          'On Dec. 28, 1902, she and Emmitt Levant were joined in holy matrimony. Annie and Emmitt farmed in various locations until her father Pompey B. Hines died in 1919, when she inherited her share of the 450 acres. Their 10 children were born on this farm.',
          'In 1941, the Federal Government seized their land for military use. Good fortune smiled upon the family. Emmitt learned of a loan a Claxton bank was about to call in, and was told that if he could pay off the remaining balance, approximately $800.00, he could have a 230-acre farm across the river in Evans County, Georgia.',
          'A devoted, lifelong member of Jerusalem Baptist Church. She was 89 years old at the time of death.',
        ],
        quote:
          '"Mama and Daddy was so happy to get the farm, they thought this was a very good deal, so good that mama supposedly tipped the banker."   Fletcher Levant',
      },
      {
        id: 'edward',
        tabLabel: 'Edward Hines',
        name: 'Edward Hines',
        treeNumber: 'Family Tree 8 of 17',
        dates: 'Born 1885 · Died Sept. 15, 1952',
        paragraphs: [
          'Edward Hines was born in Liberty County Georgia and died in Savannah, Georgia. He stood 6 feet tall, medium weight, light brown complexion, and was very mild mannered.',
          'It was said that Frank was the most handsome of all the boys, and Edward was a close second, both said to be "a lady\'s man." Edward married Daisy, producing 3 children: Charles, Winton, and Jewell. He later divorced and married Geneva Hall on Apr. 3, 1927, producing one more child, Edward Pompey Hines.',
          'Edward moved to Savannah, Georgia, where he reunited with his brothers Johnny and Pompey H. He worked as a gardener in the Savannah area.',
        ],
      },
      {
        id: 'james',
        tabLabel: 'James E. Hines',
        name: 'James E. Hines, Sr.',
        treeNumber: 'Family Tree 9 of 17',
        dates: 'Born Sept. 22, 1887 · Died Jul. 26, 1965',
        quoteAfterParagraph: 2,
        paragraphs: [
          'James E. Hines, Sr. was born in Liberty County Georgia and died in Pembroke, Georgia. He stood about 6 feet tall and carried about 175 pounds on his wiry frame, medium complexion and mild mannered. Everyone called him "Jim."',
          'James married Etner Johnson on Feb. 4, 1917 in Liberty County Georgia. He was 30 years old.',
          'Jim possessed all the family traits, the willingness to work hard, the dogmatic determination to succeed, plus one more: the desire to be first. He was the first of his siblings to place education as a top priority. At a time when 5 to 6 years of elementary schooling was considered more than adequate, Jim enrolled all 3 of his children into prestigious Dorchester Academy. James E. Hines, Jr. was the 1st descendant of Pompey B. Hines to graduate from high school and the 1st to enter college.',
          'He was 78 years old at the time of death.',
        ],
        quote:
          '"Let me tell you the story of how mother and daddy met. Daddy drove his horse and buggy to the Johnson\'s house to see Aunt Katie but Aunt Katie had already left to go to a party with another fellow. My Daddy was never one to be outdone, so he asked my Mother if she would like to go for a ride on his buggy. She accepted."   Effie Dell Hines',
      },
      {
        id: 'samuel',
        tabLabel: 'Samuel Hines',
        name: 'Samuel Hines',
        treeNumber: 'Family Tree 10 of 17',
        dates: 'Born 1888 · Died Sept. 2, 1921',
        paragraphs: [
          'Samuel Hines was born in Liberty County Georgia. It has been speculated that he served in the Army. He never married and had no children.',
        ],
      },
      {
        id: 'walter',
        tabLabel: 'Walter Hines',
        name: 'Walter Hines',
        treeNumber: 'Family Tree 11 of 17',
        dates: 'Born Aug. 10, 1889 · Died Apr. 24, 1980',
        paragraphs: [
          'Walter Hines was born in Liberty County Georgia and died in Philadelphia, Pennsylvania. He stood about 6 feet tall, weighed about 200 pounds, and was very mild mannered.',
          'On Oct. 28, 1919, Walter married Esther Williams in Liberty County, Georgia, producing 2 children. The newlyweds had a serious disagreement and Esther moved to Philadelphia where she had family. Around 1925, Walter reunited with his wife in Philadelphia.',
          'For years the family was unsure of his whereabouts. He was not even present to sign the deed that sold his share of the land to the Federal Government. Then, in April 1964, after being away for 39 years, he finally came home to his sister Bessie Hines Johnson\'s funeral. It was said that Bessie was his favorite sister. It was a funeral, but everyone was happy that Walter had finally come home.',
          'He was 91 years old at the time of death.',
        ],
      },
      {
        id: 'christina',
        tabLabel: 'Christina Hines',
        name: 'Christina Hines Mack',
        treeNumber: 'Family Tree 12 of 17',
        dates: 'Born Jun. 5, 1892 · Died Apr. 12, 1982',
        paragraphs: [
          'Christina Hines was born in Liberty County Georgia and died in Pembroke, Georgia. She was the 11th child and 5th girl in the family of 18 children. She was a small person with brown complexion and long curly hair.',
          'Christina Hines married Joe Mack on Jan. 8, 1922 in Liberty County Georgia. She was 30 years old. Pastor S. M. Walker of Jerusalem Baptist Church signed the marriage license, making it likely a church celebration.',
          'Early in 1940, Joe Mack purchased approximately 25 acres of land in Groveland, Georgia, where Christina and Joe reared their 3 children: Leroy Hines, Orlando Mack, and Alexander Mack.',
          'She was a devoted, lifelong member of Jerusalem Baptist Church. She was 90 years old at the time of death.',
        ],
      },
      {
        id: 'frank',
        tabLabel: 'Frank Hines',
        name: 'Frank Hines',
        treeNumber: 'Family Tree 13 of 17',
        dates: 'Born 1894 · Died Dec. 1930',
        paragraphs: [
          'Frank Hines was born in Liberty County Georgia and died in Waycross, Georgia. He was the 12th child and 7th son. He is said to have been the most handsome of all the boys, well liked by siblings, neighbors, and friends. When Frank came home, young ladies would come from everywhere and frolic at the "Big House." Frank never married.',
          'As a young man Frank ventured away from the family to establish his own identity, moving to Waycross, Georgia. He was killed there by two men who robbed him of approximately $45.00. He was 36 years old.',
          'His brothers, led by Julian Hines, went to Waycross and claimed his body. He was laid to rest at Jerusalem Baptist Church in Liberty County Georgia.',
        ],
      },
      {
        id: 'doyle',
        tabLabel: 'Doyle L. Hines',
        name: 'Doyle L. Hines, Sr.',
        treeNumber: 'Family Tree 14 of 17',
        dates: 'Born Sept. 14, 1895 · Died Feb. 2, 1989',
        paragraphs: [
          'Doyle L. Hines was born in Liberty County Georgia and died in Pembroke, Georgia. He stood about 5 feet 9 inches and weighed 180 pounds. He was the 13th child born to Ellen and Pompey B. Hines.',
          'Doyle was drafted into the Army during WWI and trained as a cook. He was standing on the depot in Chamblee, Georgia, waiting for a troop train when he received word that Germany had surrendered and the war was over. His orders were cancelled and he returned to the farm in Liberty County.',
          'On June 12, 1927, Doyle married Celia Strickland. She was 18 and Doyle was 32. The newlyweds moved into the "Big House" where 7 children were born. When the Federal Government seized the farm in 1941, Doyle moved his family to Bryan County, sharecropping for 2 years before purchasing a farm in Pembroke, Georgia, from Dr. W.E. Smith on credit.',
          'He was forever grateful to Dr. Smith for his trust. That farm still remains in the family today.',
          'He was 93 years old at the time of death.',
        ],
      },
      {
        id: 'esther',
        tabLabel: 'Esther Hines',
        name: 'Esther Hines Simmons',
        treeNumber: 'Family Tree 15 of 17',
        dates: 'Born Sept. 14, 1897 · Died Oct. 22, 1980',
        paragraphs: [
          'Esther Hines was born in Liberty County Georgia and died in Tuskegee, Alabama. She was the 14th child and baby girl born to Ellen and Pompey B. Hines. She stood about 5 feet 5 inches and was medium weight.',
          'She was 3 years old when her mother died of fever in 1900. Her father decided she would be the first person in the family to attend high school, enrolling her in the prestigious Dorchester Academy in Liberty County Georgia, operated by the AME Church, as the State of Georgia provided only elementary education for Black children at that time.',
          'Esther married Purley Simmons on Feb. 13, 1916, producing 7 children. In November 1926, Purley was injured in an automobile accident that left him paralyzed from the neck down. As a Veteran, he was sent to the only VA hospital treating Black patients at that time, in Tuskegee, Alabama.',
          'Esther moved her 7 children to Tuskegee, and in doing so, moved her family to the mecca of Black education. She bought land, built a house, cared for her husband, and raised her children. All of them graduated from Tuskegee High School. Her daughter Mattye Lenora was the first person in the family to receive a college degree, a Bachelor of Science from Tuskegee in 1947.',
          'She was 83 years old at the time of death.',
        ],
      },
      {
        id: 'pompeyh',
        tabLabel: 'Pompey H. Hines',
        name: 'Pompey H. Hines',
        treeNumber: 'Family Tree 16 of 17',
        dates: 'Born Mar. 20, 1899 · Died May 7, 1965',
        paragraphs: [
          'Pompey H. Hines was born in Liberty County Georgia and died in Boston, Massachusetts. He stood about 5 feet 9 inches and weighed about 180 pounds. He was 21 months old when his mother died, and was raised by his father, older sisters, and brothers.',
          'He was a pipe fitter, house painter, cement finisher, glass cutter, brick mason, and carpenter. He and his father, Pompey B. Hines, were of dark complexion, but unlike his tall, lanky father, Pompey H. was slight, and he had something his father did not: charisma. All of his brothers and sisters adored him. Someone gave him the nickname "Doc" when he was young, and this is what everyone called him. He was loved from Willie, Georgia, to Boston, Massachusetts and beyond.',
          'He married Ada Douglass on Dec. 31, 1922. Their first and only child, Elizabeth, was born at the "Big House" on Apr. 8, 1923. The family eventually settled in Savannah, Georgia, around 1938. Ada died, leaving Pompey H. to raise his only child. Elizabeth later married Everette Sheppard in 1952 and moved to Boston; her father later joined them there.',
          'He was 66 years old at the time of death.',
        ],
      },
      {
        id: 'johnny',
        tabLabel: 'Johnny Hines',
        name: 'Johnny Hines',
        treeNumber: 'Family Tree 17 of 17',
        dates: 'Born Jul. 8, 1900 · Died Jul. 16, 1958',
        paragraphs: [
          'Johnny Hines was born in Liberty County Georgia and died in Savannah, Georgia. He was the baby of the family of 16 children. He stood about 5 feet 10 inches, medium weight, with a large mustache. Pompey B. Hines was 55 years old when Johnny was born.',
          'Johnny inherited the "Big House" upon the death of his father but never took possession of the property, allowing his brothers and sisters to live there. He separated himself from the family for about 20 years, working on vegetable farms at various locations in Florida.',
          'It was in Jacksonville, Florida, where he befriended a man who later became gravely ill. The gentleman asked Johnny to "see after" his two young daughters. One of the daughters was named Rose; in 1939 Johnny married Rose. She was 19 years old and he was 39. The newlyweds moved to Savannah, Georgia, where their 3 children were born.',
          'He was 58 years old at the time of death.',
        ],
      },
    ],
  },
  motto: {
    quote:
      'Your complexion may be light, medium, or dark. Your hair may be kinky, curly, or straight. Your religion may be Muslim, Catholic, or Baptist. As you can see, we are a very diverse group. Yet we have one thing in common, we are the descendants of Pompey B. Hines. We are one. We are Family.',
    accent: 'we are the descendants of Pompey B. Hines.',
    author: 'Bud Hines',
  },
  education: {
    label: 'A Legacy of Learning',
    title: 'Education:',
    accentTitle: 'The Key to Prosperity',
    intro:
      'Examining all of the documents of land purchases, Pompey B. Hines\' signature on those documents was that of an X. It is not a great revelation that Pompey B. Hines could not read nor write, the slave master did not have a need for an educated slave. Despite this handicap he became a successful farmer, and somewhere along the way he learned to count money. At the time of his death in 1919, his estate was conservatively valued at $7,731.12.',
    highlights: [
      'Pompey realized that education is the key to prosperity. At a time when 5 to 6 years of schooling was a sufficient education for Black children, Pompey decided that his baby girl would attend high school, the prestigious Dorchester Academy. In the early 1900s, the State of Georgia did not provide high school education for Black children; the AME Church operated just two high schools in the state.',
      'Mattye Lenora Simmons, BS Tuskegee University, 1947, was the first descendant of Pompey B. Hines to receive a college degree.',
    ],
    summary:
      'In a short span of 50 years, the descendants of Pompey B. Hines have obtained more than 150 college degrees. Each succeeding generation has raised the bar, inspired by those who came before.',
    degreesTitle: 'Degrees by Family Branch',
    degrees: [
      {
        branch: 'Theodore Ball Branch',
        items: [
          'Avis Ball Hagan   BS Savannah State; MS Tuskegee',
          'Brenda Hagan Malik   Tuskegee; MS Michigan State; EDS Clark Atlanta',
          'Ishan Malik   BS Tuskegee; MS Georgia State',
          'Fatima Malik   BS Tuskegee',
          'Samara Malik   BS Tuskegee',
          'Vivian Ball Randolph   BS Tuskegee',
          'Royal Randolph III   BS Clark Atlanta',
          'Milla Nease Ball Hall   BS Savannah State; MS Tuskegee',
          'Yolanda M. Hall   BS Savannah State',
          'Thomas O. Ball   BS Tuskegee',
          'Gwendolyn Ball Cooper   BS Tuskegee',
          'Marilyn Cooper   BS Tuskegee; MS Ohio State',
          'Edward Cooper   BA University of Alabama',
          'Euris B. Belle   Northwestern University',
        ],
      },
      {
        branch: 'Julian H. Hines Branch',
        items: [
          'Hector Cummings, Jr.   BS Savannah State; DDS Howard University',
          'Shirley Bush Mitchell   BA University of District of Columbia',
          'LaShundra Carter   BS Norfolk State',
          'Jason Carter   BS North Carolina A&T',
          'Hines Carter   BS North Carolina A&T',
          'Carolyn Hines   BS Georgia Southern',
        ],
      },
      {
        branch: 'Abbie Hines Clanton Branch',
        items: [
          'Catherine C. Hollingsworth   BS Medger Evers; MS Adelphia',
          'Annette Howell   BS & MED Georgia Southern',
          'Adrian Mobley   BS Bridgewater College',
          'Abbie Jones Brothers   BS Bethune Cookman',
          'Masheika Allen   BS Florida International',
          'Mashani Allen   BS University of Florida',
        ],
      },
      {
        branch: 'Annie Hines Levant Branch',
        items: [
          'Cynthia J. Lockhart   BS Jackson State',
          'Cheryl Jones   BS Jackson State',
          'Antionette Byrd   BSW University of Maryland',
          'Theron Levant   BS Mercer University',
          'Dewayne Mincey   BS South Carolina State; MA Savannah State',
          'Fayedra Levant   BS Armstrong Atlantic State',
          'Freddie Love   BS University of Louisville',
          'Lisa Paige   BS Wright State',
        ],
      },
      {
        branch: 'James E. Hines Branch',
        items: [
          'Sanford Hines   BA University of Michigan; JD Harvard University',
          'Thomas Hines   BS Savannah State; MA Lincoln University',
          'Madonna Hines   BS Montclair State',
        ],
      },
      {
        branch: 'Doyle L. Hines Branch',
        items: [
          'Shantina Hines   BS Fredonia State; MA New School',
          'Wanda Hines   BS Rochester Institute of Tech; MA New School',
          'Stanchell Hines   BS University of Pittsburgh',
          'Rudolph Hines   BS Savannah State',
          'Tanis G. Hines   BS Savannah State; MA Troy State',
          'Jefferey Bacon   BS Fairleigh Dickerson',
        ],
      },
      {
        branch: 'Esther Hines Simmons Branch',
        items: [
          'Mattye Lenora Simmons   BS Tuskegee 1947 (1st degree holder!)',
          'Stellvetta Upshaw   BS & MED Tuskegee',
          'April Upshaw   BS & MA Troy State',
          'Stenward Simmons, Sr.   BS Tuskegee; MA Auburn',
          'E. Denise Simmons   BA UMass; MA Antioch',
        ],
      },
      {
        branch: 'Pompey H. Hines Branch',
        items: [
          'Elizabeth Hines Sheppard   BS UMass; MA Wheelock College',
          'Yvonne Sheppard Wynn   BS Boston State',
          'Kimberly Sheppard   BSW Boston University',
        ],
      },
    ],
  },
  descendants: {
    label: 'From 17 to 800+',
    title: 'The',
    accentTitle: 'Seventeen Branches',
    intro:
      'From the 17 original children of Pompey B. Hines, 800+ living descendants spread across the nation, carrying forward a legacy of faith, hard work, and an unbreakable commitment to family.',
    branches: [
      {
        id: 'd-theodore',
        tabLabel: 'Theodore Ball',
        groups: [
          { type: 'branch-head', text: 'Leudelia Ball · Ollie Ball · Richard Ball' },
          { type: 'branch-head', text: 'Joe T. Ball' },
          { type: 'child', text: 'Avis Ball Hagan' },
          { type: 'grandchild', text: 'Brenda Hagan Malik · Ishan · Fatima · Samara · Dujuan Malik' },
          { type: 'grandchild', text: 'Anthony Hagan · Gigi · Anthony Jr. · Ashley Hagan' },
          { type: 'child', text: 'W. Hardin Ball' },
          { type: 'grandchild', text: 'Vivian Ball Randolph' },
          { type: 'child', text: 'Theo Warren Ball' },
          { type: 'grandchild', text: 'Valdesha Ball · Brandon Ball · Roland Ball · Euris Belle · Maurice Belle' },
          { type: 'child', text: 'Ovedia Ball' },
          { type: 'child', text: 'Mella Nease Ball Hall' },
          { type: 'grandchild', text: 'Charles Hall Jr. · Yolanda Michelle Hall · Meredith Hall' },
          { type: 'child', text: 'Gwendolyn Ball Cooper' },
          { type: 'grandchild', text: 'Kenneth D. Cooper · Jacquelyn O. Cooper · Marilyn Cooper · Ray Cooper' },
          { type: 'child', text: 'Thaddeus F. Ball' },
        ],
      },
      {
        id: 'd-julian',
        tabLabel: 'Julian Hines',
        groups: [
          { type: 'branch-head', text: 'Fleming Hines' },
          { type: 'child', text: 'Francine Hines Small · Shantee Hall' },
          { type: 'branch-head', text: 'Herschel Hines · Mary Hines McClound' },
          { type: 'branch-head', text: 'Rosemary Bell' },
          { type: 'child', text: 'Cynthia Bell Edwards · Alexander Bell · Camille Spence' },
          { type: 'branch-head', text: 'Bessie Hines Johnson' },
          { type: 'child', text: 'Paulene Johnson Steele · Annette Johnson · Yvonne Johnson Greene' },
          { type: 'branch-head', text: 'Evelyn Hines Mitchell' },
          { type: 'child', text: 'Shirley Bush · Tyrone Mitchell' },
          { type: 'branch-head', text: 'Julian P. Hines' },
          { type: 'child', text: 'Christine Hines Carter · Julian H. Hines, Sr. · Juliette Freeman' },
          { type: 'grandchild', text: 'LaShundra T. Carter · Jason Carter · Hines Carter · Ashley Sauls' },
          { type: 'branch-head', text: 'Oliver Hines' },
          { type: 'child', text: 'Frank Oliver Hines, Sr. · Marguerita Hines · Maurice Hines' },
          { type: 'branch-head', text: 'Christine Hines · Herbert Hines' },
        ],
      },
      {
        id: 'd-abbie',
        tabLabel: 'Abbie Clanton',
        groups: [
          { type: 'branch-head', text: 'Raeford Clanton · James Clanton · Alfred Clanton · Julius Clanton' },
          { type: 'branch-head', text: 'Solomon Clanton' },
          { type: 'branch-head', text: 'Martha Ann Clanton Hagan' },
          { type: 'child', text: 'Mark · Juliette · Fredrick · Mario · Benji · Patrice · Everett Hagan' },
          { type: 'branch-head', text: 'Catherine Clanton Hollingsworth' },
          { type: 'branch-head', text: 'Mary L. Mobley' },
          { type: 'child', text: 'Ellis Mobley III · Adrian Mobley · Terrance Mobley' },
          { type: 'branch-head', text: 'Annette Clanton Howell' },
          { type: 'child', text: 'Wesley · Breland · Cameron Howell' },
          { type: 'branch-head', text: 'Solomon P. Clanton · Franklin J. Clanton' },
          { type: 'branch-head', text: 'Lena Arlethia Clanton' },
          { type: 'child', text: 'Mary L. Brown · Ellen Clanton Jones' },
          { type: 'branch-head', text: 'Virginia Clanton Michaels · Josephus Clanton' },
        ],
      },
      {
        id: 'd-annie',
        tabLabel: 'Annie Levant',
        groups: [
          { type: 'branch-head', text: 'Mary Ellen Levant · Alexander Levant' },
          { type: 'branch-head', text: 'Thomas Levant' },
          { type: 'child', text: 'Mary Bell Levant · Marcel Levant Jones · Jaunita Levant Scott' },
          { type: 'branch-head', text: 'Levander Levant' },
          { type: 'child', text: 'Beretha Cooper · Betty Griffin' },
          { type: 'branch-head', text: 'Clinton Levant' },
          { type: 'branch-head', text: 'Bessie Levant Baker' },
          { type: 'child', text: 'Albert Baker · Lollie Baker Byrd · Charlie Baker · Larry Baker' },
          { type: 'branch-head', text: 'Alberta Levant · Walter Levant' },
          { type: 'child', text: 'Dorothy Levant Mincey · Theron Levant · Lee-Artis Levant · Shirley Levant · Walter Levant Jr.' },
          { type: 'branch-head', text: 'Rose Levant · Fletcher Levant' },
        ],
      },
      {
        id: 'd-james',
        tabLabel: 'James Hines',
        groups: [
          { type: 'branch-head', text: 'James E. Hines, Jr.' },
          { type: 'child', text: 'James E. Hines III · Melissa Hines' },
          { type: 'branch-head', text: 'Sandford Hines' },
          { type: 'branch-head', text: 'Tommie Hines' },
          { type: 'child', text: 'Selina Sue Hines · Hubert Hines' },
          { type: 'branch-head', text: 'Reginald Hines' },
          { type: 'child', text: 'Jeanette Hines · Madonna Hines' },
          { type: 'branch-head', text: 'Effie Dell Simpson' },
          { type: 'child', text: 'Harrison Hines · Jo Hines · Gerald Simpson · Freddie Simpson' },
          { type: 'grandchild', text: 'Francine Shepperson · LeAnn Shepperson · Kelvin Shepperson' },
        ],
      },
      {
        id: 'd-doyle',
        tabLabel: 'Doyle Hines',
        groups: [
          { type: 'branch-head', text: 'Lollie Mae Hines · Herbert L. Hines' },
          { type: 'branch-head', text: 'Samuel Hines' },
          { type: 'child', text: 'Aurelia Malloy · Tony Hines · Keith Hines · Shelia Glenn Griffin' },
          { type: 'branch-head', text: 'George Hines' },
          { type: 'child', text: 'Harvey Williams · Dewayne Freeman · Sharon Smith · Shantina Hines' },
          { type: 'branch-head', text: 'James L. Hines' },
          { type: 'child', text: 'Marcellous Hines · Anthony Hines · Wanda Hines · Trinda Hines' },
          { type: 'branch-head', text: 'Stan Hines · Doyle L. Hines, Jr. · Ernest Hines · Rudolph Hines' },
          { type: 'child', text: 'Tanis Hines · Jefferey C. Bacon' },
        ],
      },
      {
        id: 'd-esther',
        tabLabel: 'Esther Simmons',
        groups: [
          { type: 'branch-head', text: 'Lillie M. Simmons' },
          { type: 'child', text: 'Stella Upshaw · April Upshaw' },
          { type: 'branch-head', text: 'Stenward Simmons, Sr.' },
          { type: 'child', text: 'Stenward Jr. · Robin Peebles · Danny Simmons · Michelle Simmons' },
          { type: 'branch-head', text: 'M. Lenora Simmons (1st college grad!)' },
          { type: 'child', text: 'Denise Simmons · Anthony Simmons · Nadine Simmons · Jada Simmons' },
          { type: 'branch-head', text: 'Alphonso Simmons' },
          { type: 'child', text: 'Alton Simmons · Anthony Simmons · Anita Simmons Carson' },
          { type: 'branch-head', text: 'Beverly White Burnett · Purley Simmons, Jr.' },
          { type: 'child', text: 'Yalinda · Yarnell · Crystal Simmons' },
        ],
      },
      {
        id: 'd-pompeyh',
        tabLabel: 'Pompey H. Hines',
        groups: [
          { type: 'branch-head', text: 'Elizabeth Hines Sheppard' },
          { type: 'child', text: 'Jerome Sheppard · Everett Sheppard · Anthony Sheppard · Kimberly Sheppard · Tyroone Sheppard · Stephen Sheppard · Carla Porter' },
          { type: 'child', text: 'Yvonne Sheppard Wynn' },
          { type: 'grandchild', text: 'Jamal Wynn · Jaylah Wynn' },
        ],
      },
      {
        id: 'd-johnny',
        tabLabel: 'Johnny Hines',
        groups: [
          { type: 'branch-head', text: 'Elouise Hines Bythwood' },
          { type: 'child', text: 'Danelle Bythwood · Daniel Bythwood · Cedric Evans · Farrell Evans · Fredrick Evans · Kia Evans · JC Evans · Imani Evans · Danyla Bythwood · Dyasia Bythwood · Farrell Evans Jr. · Savannah Evans' },
          { type: 'branch-head', text: 'Frank Hines' },
          { type: 'branch-head', text: 'Johnny Hines' },
          { type: 'child', text: 'Johnny Hines, Jr. · Eric Frank Hines · Christopher Michael Hines' },
        ],
      },
    ],
  },
  footer: {
    logo: 'The Pompey B. Hines Foundation',
    locations: 'Liberty County, Georgia · Sand Hills Plantation · Jerusalem Baptist Church',
    dates: 'Aug. 16, 1845   Jul. 5, 1919',
    source: 'History sourced from pbhf.blogspot.com · Pompey B. Hines Family Reunion',
  },
};
